[project]
name = "quartz"
version = "0.1.0"
# Comes from `match` syntax
requires-python = ">= 3.10"

[project.scripts]
quartz = "quartz.__main__:main"

[project.urls]
Repository = "https://github.com/thatcosmicstorm/quartz"
